vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images/uploaded
            upload_destination: '%kernel.project_dir%/public/uploaded/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        covers:
            uri_prefix: /covers
            upload_destination: '%kernel.project_dir%/public/uploaded/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
